stages:
  - debug
  - release
Build Debug:
  stage: debug
  image: gcc
  script:
    - make
  only:
    - main
    - merge_requests
Build Release:
  stage: release
  image: gcc
  script:
    - make release
  only:
    - main
    - merge_requests
